version: 2.1

defaults: &defaults
  working_directory: ~/github-dark
  docker:
    - image: circleci/node:10-browsers
  environment:
    TZ: '/usr/share/zoneinfo/America/Los_Angeles'

aliases:
  # Circle related commands
  - &restore-cache
    keys:
      # Find a cache corresponding to this specific package.json checksum
      # when this file is changed, this key will fail
      - github-dark-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
      - github-dark-{{ checksum "yarn.lock" }}
      # Find the most recent cache used from any branch
      - github-dark-
  - &save-cache
    key: github-dark-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
    paths:
      - ~/.cache/yarn
      - node_modules
  # Yarn commands
  - &yarn
    name: Install Dependencies
    command: yarn install --frozen-lockfile --non-interactive --cache-folder=~/.cache/yarn

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *yarn
      - save_cache: *save-cache
      - persist_to_workspace:
          root: .
          paths:
            - .

  pr-check:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/github-dark
      - run:
          name: Check for SemVer Label
          command: yarn auto pr-check --url $CIRCLE_BUILD_URL

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/github-dark
      - run:
          name: Release
          command: yarn auto shipit -vv

workflows:
  version: 2
  build_and_test:
    jobs:
      - install

      - pr-check:
          requires:
            - install

      - release:
          requires:
            - install
          filters:
            branches:
              only:
                - master
